$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: deepseek-dp
endpoint_name: deepseek-ep
model: azureml:deepseek-llm-7b:1
code_configuration:
  code: .
  scoring_script: score.py
environment: azureml:minimal-deepseek-inf:1
instance_type: Standard_NC4as_T4_v3
instance_count: 1
